# -*- coding: utf-8 -*-
"""SHOPY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19AXPUGD3HYViF_xCsE-ZweGvWW8NRoJP
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("✅ SHOPY Project Initialized Successfully!")

orders = pd.read_csv('/content/shopee_orders.csv')
u
orders.head()

print("Shape:", orders.shape)
print("\nData Types:")
print(orders.dtypes)

print("\nSummary Statistics:")
display(orders.describe())

print("\nMissing Values Count:")
display(orders.isnull().sum())

plt.figure(figsize=(10,5))
sns.heatmap(orders.isnull(), cbar=False, cmap='coolwarm')
plt.title("Missing Values Heatmap — SHOPY Orders Data", fontsize=14, pad=12)
plt.show()

orders.columns = orders.columns.str.strip().str.lower().str.replace(' ', '_')

print(" Clean Column Names:")
print(orders.columns.tolist())

print("Duplicate Rows:", orders.duplicated().sum())
orders = orders.dropna(subset=['order_id'])
print(" Missing Order IDs Dropped")

orders['delivery_status'] = orders['delivery_status'].fillna('Unknown')
orders['delay_reason'] = orders['delay_reason'].fillna('None')
orders['logistics_partner'] = orders['logistics_partner'].fillna('Other')
orders['payment_method'] = orders['payment_method'].fillna('Unknown')

print(" Missing categorical values filled")

num_cols = ['order_value', 'final_price', 'quantity',
            'delivery_time_days', 'customer_rating',
            'satisfaction_score', 'discount_percent']

for col in num_cols:
    orders[col] = orders[col].fillna(orders[col].median())

print("Numeric columns cleaned")

orders['order_date'] = pd.to_datetime(orders['order_date'], errors='coerce')
orders['delivery_date'] = pd.to_datetime(orders['delivery_date'], errors='coerce')

missing_dates = orders['order_date'].isnull().sum()
if missing_dates > 0:
    random_dates = pd.date_range(start="2024-08-01", end="2025-09-30", periods=missing_dates)
    orders.loc[orders['order_date'].isnull(), 'order_date'] = np.random.choice(random_dates, missing_dates)

def remove_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return df[(df[column] >= lower) & (df[column] <= upper)]

orders = remove_outliers(orders, 'order_value')
orders = remove_outliers(orders, 'final_price')

cat_cols = ['region', 'product_category', 'payment_method',
            'delivery_status', 'delay_reason', 'logistics_partner']

for col in cat_cols:
    orders[col] = orders[col].astype(str).str.strip().str.title()

print("Cleaned SHOPY Orders Dataset Summary")
print("-" * 50)
print("Rows:", len(orders))
print("\nMissing values:\n", orders.isnull().sum())
print("\nDuplicates:", orders.duplicated().sum())

orders.info()

orders.to_csv('/content/shopy_orders_cleaned.csv', index=False)
print("Cleaned dataset saved as 'shopy_orders_cleaned.csv'")

customer_ids = orders['customer_id'].unique()
seller_ids = orders['seller_id'].unique()

customers = pd.DataFrame({
    'customer_id': customer_ids,
    'customer_name': ['Customer_' + str(i) for i in range(len(customer_ids))],
    'customer_email': ['customer'+str(i)+'@email.com' for i in range(len(customer_ids))],
    'customer_segment': np.random.choice(['Premium','Regular','Occasional'], len(customer_ids))
})

sellers = pd.DataFrame({
    'seller_id': seller_ids,
    'seller_name': ['Seller_' + str(i) for i in range(len(seller_ids))],
    'seller_region': np.random.choice(['North','South','East','West'], len(seller_ids))
})

customers.to_csv('/content/shopy_customers_cleaned.csv', index=False)
sellers.to_csv('/content/shopy_sellers_cleaned.csv', index=False)

orders = pd.read_csv('/content/shopy_orders_cleaned.csv')

customers = pd.read_csv('/content/shopy_customers_cleaned.csv')
sellers = pd.read_csv('/content/shopy_sellers_cleaned.csv')

print("All datasets loaded successfully")
print("Orders:", orders.shape)
print("Customers:", customers.shape)
print("Sellers:", sellers.shape)

orders_customers = orders.merge(customers, on='customer_id', how='left')
print("Orders merged with customers")
print("Shape:", orders_customers.shape)

master = orders_customers.merge(sellers, on='seller_id', how='left')
print("Orders merged with sellers")
print("Master dataset shape:", master.shape)

print(master.head())
print("\nMissing values:\n", master.isnull().sum())
print("\nColumns:\n", master.columns.tolist())

master.to_csv('/content/shopy_master_cleaned.csv', index=False)
print("Master dataset saved as 'shopy_master_cleaned.csv'")